# Generated by Django 2.1.5 on 2019-02-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20190202_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'comment_date'},
        ),
    ]
