# Generated by Django 2.1.5 on 2019-02-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20190207_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'get_latest_by': 'post_date'},
        ),
    ]
