# Generated by Django 2.1.5 on 2019-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20190210_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='Blog/img'),
        ),
    ]
