# Generated by Django 2.1.5 on 2019-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20190210_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
