# Generated by Django 2.1.5 on 2019-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20190210_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
